blank_issues_enabled: false
contact_links:
  - name: Keystone Documentation
    url: https://github.com/justaboyhai-wq/keystone/blob/main/docs/QA.md
    about: Check Keystone FAQ
  - name: Discussions
    url: https://github.com/justaboyhai-wq/keystone/discussions
    about: Ask questions or share ideas in Discussions
