blank_issues_enabled: false
contact_links:
  - name: FTMind Documentation
    url: https://github.com/justaboyhai-wq/fmind/blob/main/docs/QA.md
    about: Check FTMind FAQ
  - name: Discussions
    url: https://github.com/justaboyhai-wq/fmind/discussions
    about: Ask questions or share ideas in Discussions
