<template>
  <div class="feedback-admin">
    <div class="feedback-admin__header"><div><h1>{{ t('feedback.adminTitle') }}</h1><p>{{ t('feedback.adminDescription') }}</p></div><div class="header-actions"><t-button variant="outline" @click="exportCsv">{{ t('feedback.exportCsv') }}</t-button><t-button theme="primary" @click="load">{{ t('common.refresh') }}</t-button></div></div>
    <div class="feedback-admin__stats"><div v-for="s in statCards" :key="s.key" class="stat-card"><strong>{{ stats[s.key] || 0 }}</strong><span>{{ s.label }}</span></div></div>
    <div class="feedback-admin__filters"><t-select v-model="status" clearable :placeholder="t('feedback.filterStatus')" :options="statusOptions" /><t-select v-model="category" clearable :placeholder="t('feedback.categoryLabel')" :options="categoryOptions" /><t-button variant="outline" @click="load">{{ t('common.search') }}</t-button></div>
    <t-table row-key="id" :data="items" :columns="columns" :loading="loading" hover @row-click="open" />
    <t-drawer v-model:visible="visible" :header="t('feedback.adminDetail')" size="620px"><template v-if="detail">
      <t-descriptions bordered :column="1"><t-descriptions-item :label="t('feedback.status')"><t-tag>{{ detail.status }}</t-tag></t-descriptions-item><t-descriptions-item :label="t('feedback.categoryLabel')">{{ t(`feedback.categories.${detail.category}`) }}</t-descriptions-item><t-descriptions-item label="问题">{{ detail.question_snapshot }}</t-descriptions-item><t-descriptions-item label="回答"><pre>{{ detail.answer_snapshot }}</pre></t-descriptions-item><t-descriptions-item label="反馈">{{ detail.description }}</t-descriptions-item></t-descriptions>
      <t-form class="admin-form" label-align="top"><t-form-item label="状态"><t-select v-model="edit.status" :options="statusOptions" /></t-form-item><t-form-item label="根因"><t-input v-model="edit.root_cause" /></t-form-item><t-form-item label="处理方式"><t-input v-model="edit.resolution_action" /></t-form-item><t-form-item label="用户可见回复"><t-textarea v-model="edit.public_reply" :autosize="{minRows:3,maxRows:6}" /></t-form-item><t-form-item label="内部备注"><t-textarea v-model="edit.internal_note" :autosize="{minRows:3,maxRows:6}" /></t-form-item></t-form>
      <div class="admin-actions"><t-button theme="primary" :loading="saving" @click="save">{{ t('feedback.saveProcess') }}</t-button></div><h3>{{ t('feedback.timeline') }}</h3><div v-for="e in events" :key="e.id" class="event"><strong>{{ e.event_type }}</strong><span>{{ e.comment }}</span><small>{{ e.created_at }}</small></div>
    </template></t-drawer>
  </div>
</template>
<script setup lang="ts">
import { onMounted, ref, computed } from 'vue';import { useI18n } from 'vue-i18n';import { listAdminFeedback,getAdminFeedback,getAdminFeedbackStats,updateAdminFeedback,type AnswerFeedback } from '@/api/answer-feedback';import { MessagePlugin } from 'tdesign-vue-next'
const {t}=useI18n();const items=ref<AnswerFeedback[]>([]);const loading=ref(false);const visible=ref(false);const detail=ref<AnswerFeedback|null>(null);const events=ref<any[]>([]);const saving=ref(false);const status=ref('');const category=ref('');const edit=ref<any>({});
const stats=ref<Record<string,number>>({});const statCards=computed(()=>['pending','reviewing','needs_info','fixing','resolved','dismissed'].map(key=>({key,label:t(`feedback.statuses.${key}`)})))
const statusOptions=computed(()=>['pending','reviewing','needs_info','fixing','resolved','dismissed'].map(v=>({value:v,label:t(`feedback.statuses.${v}`)})));const categoryOptions=computed(()=>['wrong_fact','outdated','citation_mismatch','incomplete','misunderstood','unsafe','other'].map(v=>({value:v,label:t(`feedback.categories.${v}`)})));const columns=computed(()=>[{colKey:'status',title:t('feedback.status'),cell:(h:any,{row}:any)=>h('span',t(`feedback.statuses.${row.status}`))},{colKey:'category',title:t('feedback.categoryLabel'),cell:(h:any,{row}:any)=>h('span',t(`feedback.categories.${row.category}`))},{colKey:'description',title:t('feedback.descriptionLabel'),ellipsis:true},{colKey:'created_at',title:t('feedback.createdAt')}]);
async function load(){loading.value=true;try{const [r,s]=await Promise.all([listAdminFeedback({status:status.value,category:category.value,page:1,page_size:50}),getAdminFeedbackStats()]);items.value=r.data||[];stats.value=s.data||{}}finally{loading.value=false}}async function open({row}:any){const r=await getAdminFeedback(row.id);detail.value=r.data;events.value=r.events||[];edit.value={status:r.data.status,root_cause:r.data.root_cause||'',resolution_action:r.data.resolution_action||'',public_reply:r.data.public_reply||'',internal_note:r.data.internal_note||''};visible.value=true}async function save(){if(!detail.value)return;saving.value=true;try{const r=await updateAdminFeedback(detail.value.id,edit.value);detail.value=r.data;await load();MessagePlugin.success(t('feedback.saved'))}finally{saving.value=false}}function exportCsv(){const rows=[['id','status','category','description','created_at'],...items.value.map(x=>[x.id,x.status,x.category,x.description,x.created_at])];const blob=new Blob([rows.map(r=>r.map(v=>`"${String(v||'').replace(/"/g,'""')}"`).join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fmind-answer-feedback.csv';a.click();URL.revokeObjectURL(a.href)}onMounted(load)
</script>
<style scoped lang="less">.feedback-admin{padding:28px;max-width:1400px;margin:0 auto}.feedback-admin__header{display:flex;justify-content:space-between;align-items:flex-start}.header-actions{display:flex;gap:8px}.feedback-admin__header h1{margin:0 0 8px}.feedback-admin__header p{color:var(--td-text-color-secondary)}.feedback-admin__stats{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin:20px 0}.stat-card{padding:14px;border:1px solid var(--td-component-stroke);border-radius:8px;display:flex;flex-direction:column;gap:4px}.stat-card strong{font-size:24px}.stat-card span{color:var(--td-text-color-secondary);font-size:12px}.feedback-admin__filters{display:flex;gap:12px;margin:20px 0}.feedback-admin__filters .t-select{width:220px}.admin-form{margin-top:24px}.admin-actions{display:flex;justify-content:flex-end}.event{display:flex;gap:10px;padding:10px 0;border-bottom:1px solid var(--td-component-stroke);flex-wrap:wrap}.event small{color:var(--td-text-color-placeholder);margin-left:auto}.event span{white-space:pre-wrap}pre{white-space:pre-wrap;max-height:280px;overflow:auto}
</style>
